### ISSUE TITLE
Failed to bind port 80 on docker-compose setup

### ISSUE THREAD

**Issue by cyber01** [greenbone/gsa#3957]
### Expected behavior

It will listen on port 80 inside the container and port 9392 outside the container.

### Actual behavior

When you try to listen on port 80 inside a container, an error appears in the logs. As a result, after starting the container, it will not be accessible via 127.0.0.1:9392 because refers to port 80, which is not accessible inside the container

### Steps to reproduce

Just follow the instructions at https://greenbone.github.io/docs/latest/22.4/container/index.html and the error will appear similar to what I describe. Occurs when using docker-compose.yml without any modifications

### GVM versions

All stable images in docker (like original docker-compose.yml)

### Environment

**Operating system:**

**Installation method / source:** (packages, source installation)

Docker containers (docker-compose.yml)

### Logfiles
![2024-01-29_19-25-33](https://github.com/greenbone/gsa/assets/1358988/7f0ca0ab-88ab-457a-b326-11bda05b65fb)

```
```

**Comment by bjoernricks** [comment]
Hi,

I am sorry but I can't reproduce your issue. I've changed my config of the gsa service to:

```yml
  gsa:
    image: greenbone/gsa:stable
    restart: on-failure
    ports:
      - 127.0.0.1:80:9392
    volumes:
      - gvmd_socket_vol:/run/gvmd
    depends_on:
      - gvmd
    environment:
      GSAD_ARGS: "-f -p 80 --http-only"
```

an I am able to access GSA via my browser on port 9392. Maybe your compose file is different?
